- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure base packages
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - jq
      - conntrack
    state: present
    ansible.builtin.apt:
      update_cache: true

- name: Check if swap is active
  ansible.builtin.command: swapon --summary
  register: swap_status
  changed_when: false

- name: Disable swap if active
  ansible.builtin.command: swapoff -a
  when: swap_status.stdout != ""
  register: swapoff_result
  changed_when: true
  become: true
  # when: ansible_swaptotal_mb > 0
  # args: { warn: false }

- name: Ensure swap is disabled in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*([^#]\S*\s+\S+\s+swap\s+\S+.*)$'
    replace: '# \1'
