- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: true
