image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello.autostackops.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
