replicas: 1
logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
logstashPipeline:
  logstash.conf: |
    input {
      beats { port => 5044 }
    }
    filter { }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master.platform-elk.svc:9200"]
        index => "kubernetes-%{+YYYY.MM.dd}"
      }
    }
service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
